spring:
  config:
    activate:
      on-profile: dev

  jackson:
    time-zone: Asia/Seoul
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(AHsyxM9A8g8wHiYs1Ao7S5Lrtcuqe6E5VX5dMUTeKyZnDULppD99ZrtY10al3wgruDWWWaKEcify/hBgQ4xxzEpH6fG4Vf2MnuN6IVzMU8X6VLDbW1EI8KjC9cY6gOfl)
    username: ENC(dEU2P1q9Gh22al1j0nQOGMS4c6TBMnN3)
    password: ENC(OQXOXZaAaMtwqzKjRQoiAgdVeOe2/GmJ)
    hikari:
      data-source-properties:
        serverTimezone: Asia/Seoul

  servlet:
    multipart:
      max-file-size: 20MB

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: ENC(wvHQPgB402IXW85HHlu4kOAwZWKIrG37GCmHPa2CIoo0vMefVWzmRa1rEHNwzMWH)
        default_batch_fetch_size: ENC(vlfxBKZ6fXmAzqpH/OcG6A==)