version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${MONITORING_PASSWORD}
    depends_on:
      - prometheus
    networks:
      - monitoring_network
    volumes:
      - grafana-data:/var/lib/grafana

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki/config/loki-local-config.yaml:/etc/loki/local-config.yaml
      - ./loki/wal:/wal
    networks:
      - monitoring_network

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - /var/log:/var/log
      - ./promtail/config/promtail-local-config.yaml:/etc/promtail/promtail-local-config.yaml
    command:
      - -config.file=/etc/promtail/promtail-local-config.yaml
    networks:
      - monitoring_network
    depends_on:
      - loki

networks:
  monitoring_network:
    external: true

volumes:
  grafana-data: {}