spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
    hikari:
      data-source-properties:
        serverTimezone: Asia/Seoul
  jpa:
    hibernate:
      ddl-auto: update  # 테스트 시 자동으로 스키마 업데이트
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

logging:
  level:
    root: INFO
